export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'

export const VERSION_CREATED_SUCCESS = 'VERSION_CREATED_SUCCESS'
export const VERSION_RECEIVED_SUCCESS = 'VERSION_RECEIVED_SUCCESS'
export const VERSION_DELETED_SUCCESS = 'VERSION_DELETED_SUCCESS'
export const VERSION_UPDATED_SUCCESS = 'VERSION_UPDATED_SUCCESS'

export const SITE_CREATED_SUCCESS = 'SITE_CREATED_SUCCESS'
export const SITE_RECEIVED_SUCCESS = 'SITE_RECEIVED_SUCCESS'
export const SITE_DELETED_SUCCESS = 'SITE_DELETED_SUCCESS'
export const SITE_UPDATED_SUCCESS = 'SITE_UPDATED_SUCCESS'
